### ISSUE TITLE
Document usage of toolbox in conjunction with certbot for DNS-01 challenge.

### ISSUE THREAD

**Issue by adedommelin-ducksify** [ducksify/akamai-toolbox#12]
**Is your feature request related to a problem? Please describe.**
akamai-toolbox can be used with certbot for DNS-01 challenge, which allows out-of-band certificate generation & wildcards.

**Describe the solution you'd like**
Document all the things :)

**Describe alternatives you've considered**
Native certbot plugin => akamai-toolbox is mostly providing all the required features, so why reinventing the wheel ?

**Comment by jstenvall-ducksify** [comment]
We are making progress with this issue and expect a release within a few days.
